/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;

import javax.swing.SwingUtilities;

/**
 *
 * @author qiqi0
 */
public class AddFood extends javax.swing.JFrame {

    /**
     * Creates new form AddVehicle
     */
    public AddFood() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        FoodType = new javax.swing.ButtonGroup();
        AddFoodL = new javax.swing.JLabel();
        ItemIDL = new javax.swing.JLabel();
        ItemNameL = new javax.swing.JLabel();
        PriceL = new javax.swing.JLabel();
        PriceTF = new javax.swing.JTextField();
        ItemIDTF = new javax.swing.JTextField();
        ItemNameTF = new javax.swing.JTextField();
        SnackRB = new javax.swing.JRadioButton();
        MealRB = new javax.swing.JRadioButton();
        BeverageRB = new javax.swing.JRadioButton();
        AddB = new javax.swing.JButton();
          GoBackB = new javax.swing.JButton();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        AddFoodL.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        AddFoodL.setText("Add Food");
        getContentPane().add(AddFoodL);
        AddFoodL.setBounds(180, 20, 140, 50);

        ItemIDL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ItemIDL.setText("Item ID:");
        getContentPane().add(ItemIDL);
        ItemIDL.setBounds(70, 120, 80, 25);

        ItemNameL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ItemNameL.setText("Item Name:");
        getContentPane().add(ItemNameL);
        ItemNameL.setBounds(70, 150, 110, 25);

        PriceL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PriceL.setText("Price (RM):");
        getContentPane().add(PriceL);
        PriceL.setBounds(70, 180, 110, 25);

        PriceTF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
       
        PriceTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceTFActionPerformed(evt);
            }
        });
        getContentPane().add(PriceTF);
        PriceTF.setBounds(180, 180, 140, 30);

        ItemIDTF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
      
        ItemIDTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemIDTFActionPerformed(evt);
            }
        });
        getContentPane().add(ItemIDTF);
        ItemIDTF.setBounds(180, 120, 140, 30);

        ItemNameTF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        
        ItemNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemNameTFActionPerformed(evt);
            }
        });
        getContentPane().add(ItemNameTF);
        ItemNameTF.setBounds(180, 150, 140, 30);

        FoodType.add(SnackRB);
        SnackRB.setText("Snack");
        getContentPane().add(SnackRB);
        SnackRB.setBounds(330, 80, 98, 21);
        SnackRB.getAccessibleContext().setAccessibleName("");

        FoodType.add(MealRB);
        MealRB.setText("Meal");
        getContentPane().add(MealRB);
        MealRB.setBounds(30, 80, 49, 21);
        MealRB.getAccessibleContext().setAccessibleName("");

        FoodType.add(BeverageRB);
        BeverageRB.setText("Beverage");
        BeverageRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeverageRBActionPerformed(evt);
            }
        });
        getContentPane().add(BeverageRB);
        BeverageRB.setBounds(190, 80, 98, 21);
        BeverageRB.getAccessibleContext().setAccessibleName("");

        AddB.setText("Add");
        
        AddB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBActionPerformed(evt);
            } 
        });
        getContentPane().add(AddB);
        AddB.setBounds(170, 250, 75, 23);


         GoBackB.setText("Go Back");
         GoBackB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SwingUtilities.invokeLater(() -> {
                    new FoodOrderingSystemGUI().setVisible(true);
                    dispose(); // Close the current window after opening the new one
                });
            }
        });

        GoBackB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackBActionPerformed(evt);
            }

            private void GoBackBActionPerformed(java.awt.event.ActionEvent evt) {
                
            }
        });
        getContentPane().add(GoBackB);
        GoBackB.setBounds(250, 250, 75, 23);


        pack();
    }// </editor-fold>                        

    private void PriceTFActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void ItemIDTFActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void ItemNameTFActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void BeverageRBActionPerformed(java.awt.event.ActionEvent evt) {                                           
       
    }                                   

    private void AddBActionPerformed(java.awt.event.ActionEvent evt) {                                     
        String id = ItemIDTF.getText();
        String itemName = ItemNameTF.getText();
        String textFromTextField = PriceTF.getText();
double price = Double.parseDouble(textFromTextField);

         String selectedFoodType = "";
        
        if (SnackRB.isSelected()) {
            selectedFoodType = SnackRB.getText();
        } else if (MealRB.isSelected()) {
            selectedFoodType = MealRB.getText();
        } else if (BeverageRB.isSelected()) {
            selectedFoodType = BeverageRB.getText();
        }
System.out.println("Selected Food Type: " + id);
        System.out.println("Selected Food Type: " + itemName);
        System.out.println("Selected Food Type: " + price);

        // Add()
        if (selectedFoodType == "Beverage"){
             
             FoodOrderingSystemGUI.foodCollection.add(new Beverage(id, itemName, price, "Beverage"));

        }
       
    }                                    

                                  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton AddB;
     private javax.swing.JButton GoBackB;
    private javax.swing.JLabel AddFoodL;
    private javax.swing.JRadioButton BeverageRB;
    private javax.swing.ButtonGroup FoodType;
    private javax.swing.JLabel ItemIDL;
    private javax.swing.JTextField ItemIDTF;
    private javax.swing.JLabel ItemNameL;
    private javax.swing.JTextField ItemNameTF;
    private javax.swing.JRadioButton MealRB;
    private javax.swing.JLabel PriceL;
    private javax.swing.JTextField PriceTF;
    private javax.swing.JRadioButton SnackRB;
    // End of variables declaration                   
}
